name = "snackytrails"
pages_build_output_dir = "public"
compatibility_date = "2024-07-29"

[[env.production.d1_databases]]
binding = "POLLS_DB"
database_name = "polls"
database_id = "5306ce1d-fb50-41f8-a0ea-5394bafd7c62"
