name = "snackytrails"
pages_build_output_dir = "build"
compatibility_date = "2024-07-18"

[[env.production]]
[env.production.vars]
REACT_APP_API_HOSTNAME = "snackytrails.us"

[[env.production.d1_databases]]
binding = "POLLS_DB"
database_name = "polls"
database_id = "5306ce1d-fb50-41f8-a0ea-5394bafd7c62"

[[env.staging]]
[env.staging.vars]
REACT_APP_API_HOSTNAME = "staging.snackytrails.pages.dev"

[[env.staging.d1_databases]]
binding = "POLLS_DB"
atabase_name = "polls-staging"
database_id = "f50b0dd8-e794-4d48-8c34-9217797b2615"