name = "snackytrails"
pages_build_output_dir = "build"
compatibility_date = "2024-07-18"

[[env.production]]
[env.production.vars]
REACT_APP_API_HOSTNAME = "snackytrails.us"

[[env.production.d1_databases]]
binding = "POLLS_DB"
database_name = "polls"
database_id = "5306ce1d-fb50-41f8-a0ea-5394bafd7c62"

[[env.preview]]
[env.preview.vars]
REACT_APP_API_HOSTNAME = "preview.snackytrails.pages.dev"

[[env.preview.d1_databases]]
binding = "POLLS_DB"
atabase_name = "polls-preview"
database_id = "284f4a0b-abbb-4178-a8bd-faa8a4417ba2"